### ISSUE TITLE
attachnodes make parts unattachable due to wrong last node orientation

### ISSUE THREAD

**Issue by Alewx** [girka2k/UbioWeldContinued#39] opened 2014-10-22 08:47 UTC
The current attachnodes make it normally impossible to attach a welded part to any other parts as the last node has the wrong direction, we need a fix for that.

**Comment by girka2k** [comment] 2014-10-22 09:00
isn't it duplicate of https://github.com/girka2k/unofficailUbioWeld/issues/12 ?

**Comment by Alewx** [comment] 2014-10-22 09:02
not really, but it belongs all to the same problem, that the attachnodes, need some major improvement in the welding.
https://github.com/girka2k/unofficailUbioWeld/issues/12 means that the length of the vectors is not 1 due to scaling, and sometimes it has a totally wrong direction, like parts are rotated strangly.
This is more about that the last node in the attachnodlist needs to be one with a Vector3.up to make the part work and being attachable. so we would have as a last step need to look for a node with that and make it the last position in the list.

**Comment by girka2k** [comment] 2014-10-22 09:05
Now I understand

**Comment by girka2k** [comment] 2014-10-23 17:50
Perhaps this is the solution:
518249457d6f7283b095035c69c9f1642563c581
Warning: I hasn't tested it in SHP

**Comment by girka2k** [comment] 2014-11-01 15:30
It also works in SHP
I think the question can be considered closed

**Closed as completed by girka2k** 2014-11-01 15:30 UTC
